### ISSUE TITLE
Don't sticker with gif / video

### ISSUE THREAD

**Issue by NaldoMota1** [kaiserdj/Stickerworld#1]
which command to make sticker with git / video

**Comment by kaiserdj** [comment]
I just updated the project information with example, so you can see how it works.
No command is needed, just send photos, videos, gif to the bot.
Any suggestion, problem or doubt you tell me

**Comment by NaldoMota1** [comment]
> Acabei de atualizar as informações do projeto com exemplo, para que você possa ver como funciona.
> Nenhum comando é necessário, basta enviar fotos, vídeos, gif para o bot.
> Qualquer sugestão, problema ou dúvida que você me diga
