### ISSUE TITLE
problem making gif stickers

### ISSUE THREAD

**Issue by NaldoMota1** [kaiserdj/Stickerworld#2]
I am not able to make stickers with gif, only with photos. What will it be?

**Comment by kaiserdj** [comment]
Could you give me some detail of where you get an error or what do you do?
If you send a gif to the bot, it should automatically become a sticker and receive it.

If you get an error in the console, please send it to me

**Comment by NaldoMota1** [comment]
![CapturarBot](https://user-images.githubusercontent.com/71650872/97778750-07640700-1b58-11eb-86db-cf0b40ac3946.PNG)

I installed it again. Is there an error here?

**Comment by NaldoMota1** [comment]
![Capturarbot1](https://user-images.githubusercontent.com/71650872/97778884-244d0a00-1b59-11eb-99e9-658fcb4288e1.PNG)

**Comment by kaiserdj** [comment]
Try deleting the node_modules folder and then from a cmd with administrator permissions execute: npm install

**Comment by NaldoMota1** [comment]
> Try deleting the node_modules folder and then from a cmd with administrator permissions execute: npm install

where is that folder

**Comment by kaiserdj** [comment]
![image](https://user-images.githubusercontent.com/5487950/97779426-473de500-1b7e-11eb-81d2-73964188aa6d.png)
is at the base of the project

**Comment by NaldoMota1** [comment]
I found the folder

**Comment by NaldoMota1** [comment]
![Capturar5](https://user-images.githubusercontent.com/71650872/97779744-e4892100-1b5e-11eb-9ea5-530462e3f9b5.PNG)

I don't think so. Do you have to install another program?

**Comment by NaldoMota1** [comment]
I don't think I ran cmd as an administrator

**Comment by kaiserdj** [comment]
The normal thing to install is this:
![image](https://user-images.githubusercontent.com/5487950/97780404-be767780-1b84-11eb-91cb-26dc66f84576.png)

**Comment by kaiserdj** [comment]
Have you modified any of the code?

**Comment by NaldoMota1** [comment]
> Você modificou algum código?

No. As an administrator, the same error occurs. I can make stickers with a photo, but with gif I can't

**Comment by kaiserdj** [comment]
In the first execution of the bot, you should download the file: ffmpeg.exe
![image](https://user-images.githubusercontent.com/5487950/97780835-5d03d800-1b87-11eb-9f22-e563c67089ad.png)
Check that you have this file in the root of the project

**Comment by NaldoMota1** [comment]
> Na primeira execução do bot, você deve baixar o arquivo: ffmpeg.exe Verifique se você tem este arquivo na raiz do projeto
> ![imagem](https://user-images.githubusercontent.com/5487950/97780835-5d03d800-1b87-11eb-9f22-e563c67089ad.png)

I don't have this file. How to download it

**Comment by kaiserdj** [comment]
![image](https://user-images.githubusercontent.com/5487950/97780952-3abe8a00-1b88-11eb-9d73-cc2f0ec80269.png)
The bot when executing it, if it does not detect the file, it should automatically download the file

**Comment by NaldoMota1** [comment]
> ![imagem](https://user-images.githubusercontent.com/5487950/97780952-3abe8a00-1b88-11eb-9d73-cc2f0ec80269.png)
> O bot ao executá-lo, se não detectar o arquivo, deve baixar automaticamente o arquivo

I'll try again

**Comment by NaldoMota1** [comment]
![Capturar ffmpeg](https://user-images.githubusercontent.com/71650872/97781132-32565700-1b68-11eb-867f-c2421b5116f3.PNG)

he can't download

**Comment by kaiserdj** [comment]
Okay, that's a bug I have to fix.
While I'm working on it, you can download the file at this link: https://gofile.io/d/jDbD3g
download the file and move it to the root of the project

**Comment by kaiserdj** [comment]
When you download that file, the creation of animated stickers should already work

**Comment by NaldoMota1** [comment]
yes, now it worked. Only some stickers come out very small.

**Comment by NaldoMota1** [comment]
Not all, just a few

**Comment by kaiserdj** [comment]
This is a difficult problem to deal with, when stickers are created with smaller sizes it is due to the resolution of the gif that has been sent (it is small).
It could be rescaled, but that would mean a big increase in the final size of the sticker file and whatsapp has a limitation of 1mb.
For now, it is programmed so that the gifs with resolutions smaller than 320: 320, keep the size, center it and create an invisible background.
I am working to be able to resize them to a normal size

**Comment by kaiserdj** [comment]
With the modification 2024bb4d0a686068fc16f61a73ede78f56cb6026, it should now be possible to download the ffmpeg file without problems.

I mark the issue as solved, any problem you tell me
