### ISSUE TITLE
Hello I am having Error: spawn UNKNOWN, look the image! Please help me, I'm windows 10 32bits

### ISSUE THREAD

**Issue by franlopes22** [kaiserdj/Stickerworld#21]
(node:4340) UnhandledPromiseRejectionWarning: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at spawn (child_process.js:553:9)
    at C:\Users\franc\Stickerworld\node_modules\fluent-ffmpeg\lib\ffprobe.js:155:21
    at FfmpegCommand.proto._getFfprobePath (C:\Users\franc\Stickerworld\node_modules\fluent-ffmpeg\lib\capabilities.js:144:14)
    at FfmpegCommand.proto.ffprobe (C:\Users\franc\Stickerworld\node_modules\fluent-ffmpeg\lib\ffprobe.js:141:10)
    at Function.FfmpegCommand.ffprobe (C:\Users\franc\Stickerworld\node_modules\fluent-ffmpeg\lib\fluent-ffmpeg.js:221:20)
    at C:\Users\franc\Stickerworld\lib\ffmpeg.js:87:17
    at new Promise (<anonymous>)
    at Object.ffprobe (C:\Users\franc\Stickerworld\lib\ffmpeg.js:86:12)
    at Video.<anonymous> (C:\Users\franc\Stickerworld\lib\video.js:14:42)
(Use node --trace-warnings ... to show where the warning was created)
(node:4340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:4340) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

![image](https://user-images.githubusercontent.com/76616161/103162523-71073700-47d0-11eb-987a-bd458aee16fc.jpeg)

**Comment by kaiserdj** [comment]
I am on vacation for Christmas parties and I do not have access to the pc to work, when I return home I will look at that problem more closely.

But could you please check in the StickerWorld folder, if inside the "tools" folder there is a folder called "ffmpeg" and inside there must be two exe files:
-ffmpeg.exe
-ffprobe.exe
![image](https://user-images.githubusercontent.com/5487950/103218025-42957300-491a-11eb-9fa6-ebd0b979f79a.png)
The folder has to be like this capture
Sorry for not being able to fix it now

**Comment by franlopes22** [comment]
![image](https://user-images.githubusercontent.com/76616161/103218588-297cca00-48fa-11eb-96a6-332717bfc499.jpeg)

Good Morning, 
Yes, look

**Comment by franlopes22** [comment]
oh, i opened it and it appeared that the program cannot be run because it is not my pc version.  maybe 64bit, my pc is 32bit

**Comment by franlopes22** [comment]
Now I'm getting this error ![image](https://user-images.githubusercontent.com/76616161/103219617-fe47aa00-48fc-11eb-813e-8b516bd7f77d.jpeg)

**Comment by franlopes22** [comment]
I will show you the whole process, right?  Make sure I'm Windows 32bit, I don't know if that interferes in anything.![image](https://user-images.githubusercontent.com/76616161/103445882-fd45ae00-4c57-11eb-9f76-15f0632f025e.jpeg)![image](https://user-images.githubusercontent.com/76616161/103445885-020a6200-4c58-11eb-8773-961b0e9856cc.jpeg)![image](https://user-images.githubusercontent.com/76616161/103445887-0767ac80-4c58-11eb-87da-76c286adcd73.jpeg)

**Comment by franlopes22** [comment]
Look "this application cannot be run on your pc" maybe because My pc is 32bits and this version is 64bits. Help me correct it ![image](https://user-images.githubusercontent.com/76616161/103446292-bb6b3680-4c5c-11eb-94f8-396f4fe69ee6.jpeg)

**Comment by franlopes22** [comment]
I’ve been waiting for a long time🤦🏻‍♀️

**Comment by franlopes22** [comment]
![image](https://user-images.githubusercontent.com/76616161/103551950-e4bcda00-4e89-11eb-87a5-b3333d3362fd.jpeg)

**Comment by kaiserdj** [comment]
With this change(https://github.com/kaiserdj/Stickerworld/commit/509f2e0b2fe080af0c6c6f94601129a86aec369c) it is already assumed that it could work perfectly in x32
Delete everything you have and download the latest version of the project

**Comment by kaiserdj** [comment]
Sorry for taking so long to answer, I had personal problems

**Comment by franlopes22** [comment]
Alright, I will try again later, and I will let u know if it worked to me, thank you ☺️

**Comment by franlopes22** [comment]
![image](https://user-images.githubusercontent.com/76616161/104600147-6285a000-5657-11eb-96d5-be1ccfbeea76.jpeg) 
Look 🤦🏻‍♀️

**Comment by franlopes22** [comment]
🤦🏻‍♀️ why![image](https://user-images.githubusercontent.com/76616161/104612267-c5c9ff00-5664-11eb-9165-929c69e86203.jpeg)

**Comment by kaiserdj** [comment]
Sorry for the problems, I don't have a 32-bit system, so I can't test if it works correctly.

Please could you download these files:
https://gofile.io/d/2A81cq
https://gofile.io/d/iXzMuO
And place them inside the folder: tools / ffmpeg, as I show in the image:
![image](https://user-images.githubusercontent.com/5487950/104615014-17848080-5689-11eb-9464-e56eb3848b89.png)

Sorry again for the problems

**Comment by franlopes22** [comment]
![image](https://user-images.githubusercontent.com/76616161/104617910-cbc2de80-566a-11eb-996b-3865efda4491.jpeg)

**Comment by kaiserdj** [comment]
The truth is, I am quite lost with this error, I try to search for information and I can't find anything anywhere and I can't do tests since I don't have a 32-bit computer.

The only thing I can think of is that you try to do everything from 0, I mean, delete the whole project from stickerworld, then uninstall it from nodejs.

Install node 14.15.4 LTS version (Basically recommended), download the latest version of the Stickerworld project and run it.

If you get an error, please give me the entire text of the cmd and the log if possible.

Sorry for all these problems

**Comment by franlopes22** [comment]
Thanks for supporting ☺️
