### ISSUE TITLE
my bot is giving error when I send video and gif and when I send gif in url the sticker will stay still

### ISSUE THREAD

**Issue by Fim2007** [kaiserdj/Stickerworld#23]
my bot is giving error when sending video and gif and when sending gif in url the sticker is frozen
![image](https://user-images.githubusercontent.com/75084763/103499717-d76f0380-4e27-11eb-8cd5-537302398a5c.png)

**Comment by kaiserdj** [comment]
I am trying to work on this error, it is because you are trying to send a gif that weighs more than 1MB, which is the maximum that whatsapp allows.

**Comment by kaiserdj** [comment]
Sorry for taking so long to answer, I had personal problems

**Comment by simone7121** [comment]
I've got the same issue, there's any updates ???
Greetings

**Comment by kaiserdj** [comment]
Several changes have been made in whatsapp and in the main library that Stickerworld uses, so now it should be easier to implement a detection if it gives an error due to the size of the image / video.

I will try to work on it, in the next few days

**Comment by kaiserdj** [comment]
In the latest version it should stop giving you problems, let me know anything.

Sorry for taking time to answer and update the project, I had a very busy few months and did not have time

I close the issue for now, open it if you need.
