### ISSUE TITLE
can't run on other os

### ISSUE THREAD

**Issue by sudimantidio** [kaiserdj/Stickerworld#25]
![image_2021-01-18_193202](https://user-images.githubusercontent.com/77594127/104915870-d7dcd200-59c3-11eb-9710-0a3d357c9965.png)

please make it for linux / ubuntu I like the bot but it can't be run on my debian based vps

**Comment by kaiserdj** [comment]
It is an improvement that I have to do, but it requires a lot of time ... I will do it little by little, right now I am working on several projects

**Comment by sudimantidio** [comment]
> It is an improvement that I have to do, but it requires a lot of time ... I will do it little by little, right now I am working on several projects

I am very grateful, you have wanted to make for another OS I will wait :)

**Comment by HAMODE3389** [comment]
What is the OS for this tool ?

**Comment by kaiserdj** [comment]
In the latest version the project already allows multiplatform 😄 ❤️ 

Sorry for taking time to answer and update the project, I had a very busy few months and did not have time

I close the issue for now, open it if you need.
