### ISSUE TITLE
Error when sending: [object Object]

### ISSUE THREAD

**Issue by GladistonXD** [kaiserdj/Stickerworld#28]
### I have this error for a few days now, I can't send any type of sticker, I couldn't find a solution 🤕

**Comment by kaiserdj** [comment]
Do you have the latest version of stickerworld?

**Comment by GladistonXD** [comment]
Yes, other people also have this problem with the same method, made a topic about on venom

https://github.com/orkestral/venom/issues/587

**Comment by macieladv** [comment]
I have this error for a few days now, I can't send any type of sticker, I couldn't find a solution :'(
@kaiserdj

**Comment by kaiserdj** [comment]
> I have this error for a few days now, I can't send any type of sticker, I couldn't find a solution :'(
> @kaiserdj

 They are working on fixing the problem: https://github.com/orkestral/venom/issues/587#issuecomment-780198336

**Comment by GladistonXD** [comment]
I managed to resolve using the 'Nightly' version directly "npm i --save https://github.com/orkestral/venom/releases/download/nightly/venom-bot-nightly.tgz" 😄

**Comment by kaiserdj** [comment]
Fix: d9064921e0abbfaf924fcf33afb4e95eac78535e
