### ISSUE TITLE
Working good for images, but not for videos.

### ISSUE THREAD

**Issue by akshat7101999** [kaiserdj/Stickerworld#37]
Hi

This is working great with images but with videos it is giving an error of unhandled promise.

**Comment by akshat7101999** [comment]
**UPDATE**

I fixed the error by editing the "ffmpeg.js" file in "lib" folder. Since i am using linux(ubuntu) and you have hard coded the path of ffmpeg for windows (line 118 135 and 104 of ffmpeg.js). I edited them according to my environment and now it works like charm. 

Thanks for a great project !!

**Comment by kaiserdj** [comment]
In the latest version it should stop giving you problems, let me know anything.

Sorry for taking time to answer and update the project, I had a very busy few months and did not have time

I close the issue for now, open it if you need.
