### ISSUE TITLE
how to fix it?

### ISSUE THREAD

**Issue by dimanto019238** [kaiserdj/Stickerworld#39]
![Untitled](https://user-images.githubusercontent.com/83316548/120591292-1ac8af00-c466-11eb-9d59-60af109d2c20.png)
how to fix it?

**Comment by Dogepot2** [comment]
I have the exact same problem

![image](https://user-images.githubusercontent.com/43354165/120601838-694f5c80-c418-11eb-9a8a-4f9dcc73210f.png)

**Comment by Dogepot2** [comment]
Found a fix by GladistonXD!
https://github.com/kaiserdj/Stickerworld/issues/28#issuecomment-781877149

**Comment by kaiserdj** [comment]
I did not understand, was the problem solved or not?

**Comment by rubber487** [comment]
> 
> 
> I did not understand, was the problem solved or not?

after npm i then use the command "npm i --save https://github.com/orkestral/venom/releases/download/nightly/venom-bot-nightly.tgz" and it worked

**Comment by Viniuau** [comment]
Certain GIFs are also returning this error. Static stickers are working fine, but it's 50/50 when it comes to GIFs.
![image](https://user-images.githubusercontent.com/19510529/120845714-90f11280-c547-11eb-8271-3ff6c047872e.png)

**Comment by kaiserdj** [comment]
@Viniuau Normally it is that the gif that is received occupies more than 1mb and whatsapp does not allow stickers with a weight greater than 1mb
Could you check how big are those gifs you sent?

**Comment by Viniuau** [comment]
They were all less than 1mb. The heaviest GIF was 0.93mb.

**Comment by kaiserdj** [comment]
Could you send me a gif of those that give you an error to test with?

**Comment by Viniuau** [comment]
These are GIFs that failed to convert, straight from WhatsApp. There's more, but these are the only SFW ones that people sent to the bot.
https://user-images.githubusercontent.com/19510529/121115038-fd3f7080-c7ea-11eb-8721-6d6d946aa845.mp4
https://user-images.githubusercontent.com/19510529/121115050-ffa1ca80-c7ea-11eb-8b36-8bb6decf2915.mp4

**Comment by johnparkerg** [comment]
This should probably be a separate issue, but I'm dealing with the same thing.

**Comment by Viniuau** [comment]
Now the bot just doesn't work. It always returns **"rejected by customActiveCommand: No matches found"**

**Comment by kaiserdj** [comment]
> Now the bot just doesn't work. It always returns **"rejected by customActiveCommand: No matches found"**

Please, when you have a problem, search among the issues if there is someone who is the same as you and if not, create an issue yourself.

And it is not an error, you have the ActiveCommand option activated in the configuration: https://github.com/kaiserdj/Stickerworld/blob/07ec057765f8712777fe5f72b8cb6da52c7f8ede/config.json#L9

Disable it and you're done

**Comment by kaiserdj** [comment]
> These are GIFs that failed to convert, straight from WhatsApp. There's more, but these are the only SFW ones that people sent to the bot.
> https://user-images.githubusercontent.com/19510529/121115038-fd3f7080-c7ea-11eb-8721-6d6d946aa845.mp4
> https://user-images.githubusercontent.com/19510529/121115050-ffa1ca80-c7ea-11eb-8b36-8bb6decf2915.mp4
> 
> Edit: It seems to be a problem with individual files. I've tested with a video I uploaded as a GIF and the bot didn't convert. I cropped it to 4:3 and then 1:1 and even then I got the same error. I tried shrinking the GIF duration directly through WhatsApp and I got the same result. The only thing that I haven't tested was to cut the video (that is, shorten its duration) before sending it.

I'm doing tests to try to fix that problem, thanks for the gifs and sorry for the problems

I will close this issue, since the initial problem is solved

> This should probably be a separate issue, but I'm dealing with the same thing.

You are absolutely right, can you please create another issue for this problem?

**Comment by Viniuau** [comment]
> > Now the bot just doesn't work. It always returns **"rejected by customActiveCommand: No matches found"**
> 
> Please, when you have a problem, search among the issues if there is someone who is the same as you and if not, create an issue yourself.
> 
> And it is not an error, you have the ActiveCommand option activated in the configuration:
> 
> https://github.com/kaiserdj/Stickerworld/blob/07ec057765f8712777fe5f72b8cb6da52c7f8ede/config.json#L9
> 
> Disable it and you're done

Oops, my bad. I do search for existing issues, but I forgot to do it this time. Won't happen again.
Thanks for looking into it.
