### ISSUE TITLE
Type error Cannot read property 'modelClass' of undeifned

### ISSUE THREAD

**Issue by adapacnu** [kaiserdj/Stickerworld#4]
![2020-11-06 14_30_08-Window](https://user-images.githubusercontent.com/34007225/98407307-72707a80-203d-11eb-81ae-62e4bfd5a3b2.png)

Previously it worked fine but from last day am getting above error.

**Comment by kaiserdj** [comment]
It is a problem with the Wapi library (WhatsApp Web driver), they have updated the web and changed the way it works.

We have to wait for the Wapi library to update and when they release the patch, I update the library.

Any news or changes, I will notify you

Thank you very much for letting me know and I'm sorry that I can't fix it right now.

**Comment by adapacnu** [comment]
Thank you for the update bro.. :-)
