### ISSUE TITLE
any news?

### ISSUE THREAD

**Issue by NaldoMota1** [kaiserdj/Stickerworld#5]

**Comment by adapacnu** [comment]
Bro any updates on whatsapp lib?

**Comment by kaiserdj** [comment]
Hi, sorry for not being able to answer yesterday, I was busy with work.

The problem library is https://github.com/orkestral/venom (Venom), and they already made a patch for this problem, they just haven't released a new version.

But if you already need Stickerworld, you can create the dependency with the latest version, the steps you must do are the following:

- Next to the Stickerworld folder clone the venom repository: https://github.com/orkestral/venom.git
![image](https://user-images.githubusercontent.com/5487950/99077421-06ea5800-25bd-11eb-86d5-ae04f8eb97f9.png)
- Within the venom project run the following commands in order:

```
> npm i
> npm run build:wapi
> npm run build:middleware
> npm run build:jsQR
> npm run build
```
- In the Stickerworld project uninstall the venom-bot dependency: `npm uninstall venom-bot`

- From a terminal with administrator permissions and in the Stickerworld project folder, execute: `npm i ..\venom`

- Then again run(in the Stickerworld project): `npm i`

The result should look like this in the package.json file
![image](https://user-images.githubusercontent.com/5487950/99077964-deaf2900-25bd-11eb-8339-3f38ff4aa3c8.png)

And you could already run the project normally

Sample of correct execution with the previous steps:
![Code_-_Insiders_41nXLrit3I](https://user-images.githubusercontent.com/5487950/99078027-fb4b6100-25bd-11eb-9d7a-53e5763b9cb5.png)

I can do nothing more than explain how you can do it ... when they update the official dependency, I will publish an update of the project

I hope it helps you and any problem, send me a message

**Comment by kaiserdj** [comment]
Btw the commits of the venom patches are these:
- https://github.com/orkestral/venom/commit/9166c6821e1c91c446478e4584c9ef0304f081f1
- https://github.com/orkestral/venom/commit/f8feaae74b71328ac0ab541cdea15c939a4308a2

**Comment by adapacnu** [comment]
Thanks very much bro.. it's working 👍
