### ISSUE TITLE
I can't understand how send images to the bot

### ISSUE THREAD

**Issue by l13rb4git** [kaiserdj/Stickerworld#52]
the log: 

\> stickerworld@2.1.1 start /home/macunaima/codes/Stickerworld
\> node index

info:     [session] Initializing browser wss...
Chrome not found, using chromium
info:     [session] Browser successfully opened
info:     [session] checking headless...
info:     [session] headless option is active, browser hidden
info:     [session] Checking page...
info:     [session] Page successfully accessed

and  after read the QR code:

✓ [instance: session]: Connected
Session started
[0d187518e9756caffd545b2a154dae6c] New group message: group-name, for user: user-number
[0d187518e9756caffd545b2a154dae6c] Url no detected

What is the number for the bot?

**Comment by Zi5han** [comment]
The number of the bot is the one from which WhatsApp account you have scanned the QR-Code. If you scanned the QR-Code with your own phone with your own WhatApp account/number then that is the number of the bot. Though only others can create stickers by sending YOU (bot) the image/gif/video with the message "!sticker" or "!Sticker", you can not create stickers by sending it to yourself from the same number (_would be cool if the developers add this feature_)

**Comment by l13rb4git** [comment]
thx for the explanation 🤗
