### ISSUE TITLE
the sticker is accelerating  

### ISSUE THREAD

**Issue by Sambosa711** [kaiserdj/Stickerworld#8]
I would like to thank you for the robot I liked it very much
I have a problem, the sticker is accelerating +
Hope you added rights to the sticker and auto responder
And thank you for your great effort

**Comment by ry2n711** [comment]
![Screenshot_20201210_193540_com whatsapp](https://user-images.githubusercontent.com/36896768/101801004-f7f4b800-3b1e-11eb-919a-4e208477d669.jpg)
![Screenshot_20201210_193549_com whatsapp](https://user-images.githubusercontent.com/36896768/101801041-0347e380-3b1f-11eb-8b36-3ffa1bd87af1.jpg)

I hope you add rights like

**Comment by ry2n711** [comment]
And to add a message, enjoy the poster
![Screenshot_20201210_193857](https://user-images.githubusercontent.com/36896768/101801463-6b96c500-3b1f-11eb-9fde-0e3888ec107f.jpg)

**Comment by kaiserdj** [comment]
Thanks for the suggestions, I'll work on them in the new version, for now I think I have solved the problem of the stickers being accelerated.

I hope I can upload a finished version this weekend

**Comment by ry2n711** [comment]
You pleased me with this news, thank you very much

**Comment by HugoLibanori** [comment]
When do you want to launch the update?

**Comment by ry2n711** [comment]
Thank you, I want now if you can

في الأحد، ١٣ ديسمبر، ٢٠٢٠ ٤:٢٦ م HugoLibanori <notifications@github.com>
كتب:

**Comment by kaiserdj** [comment]
Unforeseen events arose this weekend and I have not been able to dedicate all the hours I wanted to the project, so I will surely not have time to publish the new update.

I have published a new branch, where I will publish all the advances of the new version. It is in development, do not try to use it as the old version because it does not have all the functions yet.

https://github.com/kaiserdj/Stickerworld/tree/2.0

I am very sorry for the delay and hope I can finish it in this next week

**Comment by ry2n711** [comment]
Do not apologize, we appreciate your circumstances. Thanks in advance =)

**Comment by kaiserdj** [comment]
I'm still working on it, but there is already a very beta version.
You can try it if you want by downloading branch 2.0: https://github.com/kaiserdj/Stickerworld/tree/2.0
and running `npm test`
It is normal that it has bugs or functions not yet added

**Comment by ry2n711** [comment]
Thank you for your great effort
Version 2.0 has been tried
Works great with images and links
But when I send a video or GIF, it sometimes turns it into a poster
Mostly I get a message

(node:10724) UnhandledPromiseRejectionWarning: Error: Evaluation failed: n
    at ExecutionContext._evaluateInternal (C:\Users\ryan\Desktop\Stickerworld-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\ryan\Desktop\Stickerworld-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

**Comment by ry2n711** [comment]
![‏‏لقطة الشاشة (1)](https://user-images.githubusercontent.com/36896768/102895370-a0870e00-4475-11eb-92e4-0897b89cde92.png)

**Comment by ry2n711** [comment]
‫في الثلاثاء، 22 ديسمبر 2020 في 11:37 م تمت كتابة ما يلي بواسطة ريان
المالكي <‪ry2n711@gmail.com‬‏>:‬

> I designed a simple logo
> Hope you like it
>
>
>
>

**Comment by ry2n711** [comment]
I designed a simple logo
Hope you like it

‫في الثلاثاء، 22 ديسمبر 2020 في 11:42 م تمت كتابة ما يلي بواسطة ريان
المالكي <‪ry2n711@gmail.com‬‏>:‬

>
>
> ‫في الثلاثاء، 22 ديسمبر 2020 في 11:37 م تمت كتابة ما يلي بواسطة ريان
> المالكي <‪ry2n711@gmail.com‬‏>:‬
>
>> I designed a simple logo
>> Hope you like it
>>
>>
>>
>>

**Comment by kaiserdj** [comment]
After investing a lot, the error is due to the fact that WhatsApp has a limit on the size of the animated stickers, so if you try to convert something very heavy into a sticker, it returns an error.

I am working on an option to try to compress the videos if necessary and be able to send them. And if it is still very heavy, it returns a message that the file is heavy

**Comment by ry2n711** [comment]
Thank you, I wish you success

**Comment by limter1** [comment]
> After investing a lot, the error is due to the fact that WhatsApp has a limit on the size of the animated stickers, so if you try to convert something very heavy into a sticker, it returns an error.
> 
> I am working on an option to try to compress the videos if necessary and be able to send them. And if it is still very heavy, it returns a message that the file is heavy


Is the video compression issue resolved?

**Comment by kaiserdj** [comment]
I have not had time to work on the project, a lot of work from my studies and other projects ...

I hope to return to this project this or next week, to solve this error

**Comment by limter1** [comment]
Thank you for your efforts

**Comment by kaiserdj** [comment]
In the latest version it should stop giving you problems, let me know anything.

Sorry for taking time to answer and update the project, I had a very busy few months and did not have time

I close the issue for now, open it if you need.
